[package]
name = "camera-rig"
version = "0.1.0"
authors = ["Lamar Daughma <lite5h4dow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
